### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [prometheus/docs#2181]
This is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to:
  - A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), 
  which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stage 1 (no code changes are necessary)

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-80ZM8LGB96`**
- [x] [Connect] to the GA4 site tag from the UA tag.

### Tasks: stage 1b - upgrade to use `gtag.js`

- [x] Upgrade website to use [gtag.js] library - #2207
- [x] ~Use GA4 setup assistant to "reconnect" the two tags.~ Can't use the GA4 setup assistant to connect site tags from different accounts it would seem.
- [x] Confirm that the GA4 site tag is receiving events
- [x] Confirm that the UA site tag, `UA-58468480-1`, is still receiving events

### Tasks: stages 2 & 3

- [x] [Connect] UA ID from GA4 site tag
- [x] Configure GA4 ID through [Netlify snippet injection], "Google Analytics 4 - only in production", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-80ZM8LGB96"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-80ZM8LGB96');
  </script>
  {% endif %}
  ```
- [x] Dis[connect] to the GA4 site tag from the UA tag
- [x] Confirm that the GA4 site tag is receiving events and that the UA site tag, `UA-58468480-1`, is still receiving events:
  > <img width="600" alt="image" src="https://user-images.githubusercontent.com/4140793/201354527-39073838-2d88-442b-b4eb-250439137133.png">

### Related

- https://github.com/promcon/website/issues/245
- Followup: #2234

### More:

- #2208
- #2209
- #2210

/cc @nate-double-u @caniszczyk 

---

Current website analytics info:

- UA site tags:
  - `UA-58468480-1`, main and actively used tag.
  - `UA-58468480-2`: a tag planned for use over a separately deployed blog, but it seems that it never used in production AFAICT, only during test deploys from 2015-2016 (GA screenshot to be added shortly).
  - `UA-58468480-3` is the tag actively used for [promcon.io](https://promcon.io)

Hugo layout relevant for the main tag:

- https://github.com/prometheus/docs/blob/918a96509582678fafb35f5dc9f35dcaea7591e4/layouts/footer.html#L9-L18

---

Previous issue on this topic: #2175.

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
@bwplotka @RichiH @juliusv: can one of you grant me access to your UA analytics account?

Note that we'll be creating the new GA4 site tag under the CNCF analytics account.

**Comment by chalin** [comment]
I'll also either need access to your **Netlify account**, or have someone able to add an environment variable for me when the time comes (stage 2).

**Comment by juliusv** [comment]
@chalin Sure, could you let me know your email address for both of these? Feel free to send to julius.volz@gmail.com.

**Comment by LKaemmerling** [comment]
Hello @juliusv, @chalin and the rest,

I'm sure this is not the right place, but I wanted to bring to your attention that Google Analytics is not a privacy-friendly service. Would you consider moving to privacy first analytics solution like https://usefathom.com/? This would bring a lot of benefits for users, as it is faster than Google Analytics and also respects the privacy of the users.

**Comment by juliusv** [comment]
@LKaemmerling Well personally, I totally agree and only use plausible.io these days, which also aims to be a GDPR-compatible and very ligh-weight alternative to GA.

However, it seems like the LF / CNCF uses GA to track all their different project websites. But maybe you can convince them to switch at some point :)

**Comment by chalin** [comment]
> seems like the LF / CNCF uses GA to track all their different project websites.

Right. For the moment, the CNCF will continue using GA.

**Comment by chalin** [comment]
Migration stages 2 & 3 are complete. GA4 ID is now setup via snippet injection.
